version: '3'
services:
  
  nodejs:
    build: ./nodejs
    container_name: nodejs
    command: ["pm2-runtime", "/codebase/api/app/app.yml"]
    env_file:
      - .env
    volumes:
      - '../app:/codebase/api/app'
    ports:
      - '80:3000'
      
volumes: 
  database-volume: